### ISSUE TITLE
Seed setting

### ISSUE THREAD

**Issue by soy-cat** [fogellab/multiWGCNA#22]
Hi there,

I'm wondering whether setting a seed is necessary for effective multiWGCNA analysis. I understand that it allows for reproducibility, but when I set a seed of 2000 my expression data appear to shrink down to a list of only 2000 genes from around 45000 genes. I noticed the astrocyte vignette does not set a seed, but the autism vignette does set a seed.

Is setting the seed important/necessary for this analysis? Any guidance would be much appreciated!

**Comment by dariotommasini** [comment]
Hi @soy-cat , 

I think there is a bug in your code. Setting a seed should not affect your data, it should only affect random number generation in functions like sample. Please paste a minimal reproducible example and I can help you troubleshoot. The only reason I set a seed in the autism vignette is because we are downsampling to 2000 genes in that vignette to make it faster, whereas in the astrocyte vignette we use all genes.

**Comment by soy-cat** [comment]
Hi @dariotommasini ,

Thanks for your quick reply. You're right, I did have a bug right after my seed setting where I was overwriting my expression table, this is where I got mixed up. I removed the line and I'm able to run it on the full set of genes now, thank you for bringing this to my attention!
