### ISSUE TITLE
Preservation p-values

### ISSUE THREAD

**Issue by GettyScience** [fogellab/multiWGCNA#7]
Hello,

I have been working with your program for a number of months and things are going really well. I am in the homestretch for my research and am trying a few things for better results. I have found good results from the preservation analysis, some modules only existing in some groups, based on the plots. However, when I write the results to a sheet I can use later, the p-value used to determine significance is not listed. I can see the preservations score, as well as others, but not the p-value. 

Is there a way to export that significance value for the preservation tests? And what is the meaning of the other values given in this export? Are they used to calculate the significance? 

Any help is appreciated. 

Thank you,

**Comment by GettyScience** [comment]
Hello, I am just following up on this request. Thank you,

**Comment by dariotommasini** [comment]
Hi @GettyScience 

Sorry for the late reply. 

Short answer: 
You need to run diseasePreservationPTest function. However, I removed it at some point when submitting to Bioconductor because it had some issues. Give me a couple days to add it back to the development release, then please re-install multiWGCNA from github using devtools. I'll add an example in the documentation to make it clear how to run the function. 

Long answer: 
The preservation comparisons function simply runs the WGCNA preservation analysis on the WGCNAObject list supplied. The WGCNA preservation analysis does not report p-values, it reports a number of statistics that are often summarized using the z-summary preservation score. What we and others have done in the past to see if a preservation score is lower or higher than expected by chance is implement a permutation test where you derive the null distribution of preservation scores for the dataset by shuffling the labels of interest. For example, in the multiWGCNA paper, we observe a preservation score of about 9 for our module of interest (dM15 from disease data) in the wildtype data. The question is this: what is the probability of getting the observed preservation score if we randomly split the dataset rather than using the true phenotype labels (disease vs wildtype). It turns out that the expected preservation score for a module the size of dM15 is around 20. In fact, out of the 2000 permutations we ran, only 39 of them were less than or equal to the score we observed, which corresponds to a p-value of 39/2000 = 0.0195. Since each permutation requires a network construction on split1 and a preservation on split2, this is a very slow step, which is why it is not part of the standard multiWGCNA pipeline. I recommend running this analysis on a computing cluster. 

Hope that helps

**Comment by GettyScience** [comment]
Okay, thank you! I was confused when the plot constructed by the preservation analysis contained a p-value, but not the results sent to text. The plot I produced was unhelpful simply due to overlap (so not all modules had a discernible name attached).

**Comment by dariotommasini** [comment]
Hi @GettyScience, 

I'm not sure what p-values you're referring to. Which command generated those plots? Could you upload the plot here? 

I apologize, re-implementing the permutation test is going to take me a bit longer than expected because some of the functions I used are deprecated. Rather than slow you down, in the meantime here is the code I used, which could serve as a guide for your analysis: 

```
referenceDatExpr=read.csv(args[1])
design=read.csv(args[2])
nPermutations=500; refColumn=3; testColumn=2
	
	nCores=15
	registerDoParallel(cores=nCores)
	enableWGCNAThreads(nThreads=nCores)
	
	datExpr=referenceDatExpr[,match(design$Sample, colnames(referenceDatExpr))]
	
	wtDatExpr=list()
	dsDatExpr=list()
	WGCNAobjects=list()
	preservationData=list()
	filteredPreservationData=list()

	for(permutation in 1:nPermutations){
		#assign phenotype labels randomly
		WT.indices=list()
		conditions=unique(design[, refColumn])
		for(condition in conditions){
			conditionalDesign=design[design[, refColumn]==condition,]
			nSamples=nrow(conditionalDesign)
			nWT=nrow(conditionalDesign[conditionalDesign[, testColumn]=="WT",])
			sampleIndices=which(design[, refColumn]==condition)
			WT.indices=append(WT.indices, sampleIndices[sample(1:nSamples, nWT, replace=F)])
		}
		WT.indices=unlist(WT.indices)
		randomHealthy=datExpr[, WT.indices]	
		randomHealthy=data.frame(X=referenceDatExpr$X, randomHealthy)
		randomDisease=datExpr[, !(1:ncol(datExpr) %in% WT.indices)]
		randomDisease=data.frame(X=referenceDatExpr$X, randomDisease)
		
		#perform WGCNA
		dir.create("WGCNAs")
		setwd("WGCNAs")
		wtDatExpr[[permutation]] <- runWGCNA_minimal(randomHealthy, paste0("WtP", permutation), softPowerCalculation=F)
		dsDatExpr[[permutation]] <- runWGCNA_minimal(randomDisease, paste0("DsP", permutation), softPowerCalculation=F)
		setwd("..")
		gc()
		
		#perform preservation
		dir.create("preservation")
		setwd("preservation")
		preservationData[[permutation]]=list()
		preservationData[[permutation]][[1]] <- getPreservation(wtDatExpr[[permutation]], dsDatExpr[[permutation]], write=T)
		preservationData[[permutation]][[2]] <- getPreservation(dsDatExpr[[permutation]], wtDatExpr[[permutation]], write=T)
		setwd("..")
		save.image("presPermutation.RData")
		WGCNAobjects[[permutation]]=findOutlierModules(findModuleEigengenes(dsDatExpr[[permutation]]))
		filteredPreservationData[[permutation]]=preservationData[[permutation]][[2]][!rownames(preservationData[[permutation]][[2]]) %in% WGCNAobjects[[permutation]]@outlierModules,]
		dir.create("filteredPreservation")
		write.csv(filteredPreservationData[[permutation]], paste0("filteredPreservation/filt", permutation, ".csv"), row.names=F)
		gc()
		save.image("presPermutation.RData")
	}

z.summary.dist=list()
module.size=list()
for(permutation in 1:nPermutations){
	myPerm=filteredPreservationData[[permutation]]
	z.summary.dist[[permutation]]=myPerm$Zsummary[which.min(abs(myPerm$moduleSize-297))]
	module.size[[permutation]]=myPerm$moduleSize[which.min(abs(myPerm$moduleSize-297))]
}
summary=cbind(z.summary.dist, module.size)
write.csv(summary, "round6_summary.csv", row.names=F)

# Permutation p-value
z.summary.dist=unlist(z.summary.dist)
below=length(z.summary.dist[z.summary.dist<9.16261490617938])
probability= below/nPermutations
probability

save.image("presPermutation.RData")
```

**Comment by GettyScience** [comment]
I used the preservation comparison plot function. The output is plots similar to below:
 
![condition1](https://github.com/fogellab/multiWGCNA/assets/139302831/13eed7b3-7eaf-4ae3-9a8b-6fcf7d65f461)

**Comment by dariotommasini** [comment]
To clarify, the p-values on the x axis are derived from the standard WGCNA pipeline e.g. to run a correlation test between your input conditions and the module eigengene. They do not refer to any preservation aspect of the module. They only tell you whether the module is associated with the conditions or not. The preservation score is on the y-axis and that tells you if the module is preserved (Z > 10), weakly preserved (10 > Z > 2) or not preserved (Z < 2). The purpose of this plot is to quickly tell if any trait-associated modules are differetially preserved. For instance, your module 7 on the left might be. 

Do make sure you increase the number of permutations, as the vignettes use few permutations for computational reasons. At least 50-100 permutations should be performed for accurate Z-summary preservation statistics.

**Comment by GettyScience** [comment]
Each time I use 1000 permutations for this test. I am still unable to use the data at times because in my more complex tests we have many modules that are differentially preserved and overlapping. So the number label gets lost. 

To clarify, though, the p-value relates to whether or not the module matches a treatment/genotype? Why when I run the preservation comparison plot for my two genotypes does it only show "treatment" modules and when I run the treatment vs control version of this preservation code it only shows "pgm" (one of the genotypes)?

**Comment by GettyScience** [comment]
<img width="601" alt="image" src="https://github.com/fogellab/multiWGCNA/assets/139302831/1abcf873-eaec-437f-8623-f39b72f5b823">

**Comment by dariotommasini** [comment]
Seems like you're getting way too many modules. You probably shouldn't get any more than 50, maybe 60 modules. What parameters are you supplying to constructNetworks? A normal call would be: 

```
astrocyte_networks = constructNetworks(astrocyte_se, sampleTable, conditions1, conditions2, 
                                  networkType = "signed", TOMType = "unsigned", 
                                  power = 12, minModuleSize = 100, maxBlockSize = 25000,
                                  reassignThreshold = 0, minKMEtoStay = 0, mergeCutHeight = 0,
                                  numericLabels = TRUE, pamRespectsDendro = FALSE, 
                                  deepSplit = 4, verbose = 3)
```

Are you sure your sample size is large enough for analyzing col and pgm separately?

**Comment by smukher2** [comment]
PLEASE HELP STOP PLAGIARISM AND VILLAINOUS SCIENTISTS BRENT FOGEL (UCLA) AND DARIO TOMMASINI (now PhD student in UC Berkeley) BY NOT CITING OR USING THIS, OR THEIR OTHER CODES AND PAPERS BY THEM. INSTEAD USE AND CITE THE ORIGINAL WORKS (WITH VIDEO TUTORIAL) BY DR. STEVE HORVATH, DR. PETER LANGFELDER AND DR. JEREMY MILLER.(details below)

*For details about wrong doings by Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini
please see open letter at http://tinyurl.com/bde788x2 or file 'This To Apprise You About Wrong Doings By Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini.pdf' posted at https://gitlab.com/smukher2/openletter that I also emailed to UCLA, UC Berkeley, iScience and BMC Bioinformatics reporting plagiarism by Brent Fogel and Dario Tommasini in their two papers using this multiWGCNA code https://github.com/fogellab/multiWGCNA:
Tommasini D, Fox R, Ngo KJ, Hinman JD, Fogel BL. Alterations in oligodendrocyte transcriptional networks reveal region-specific vulnerabilities to neurological disease. iScience. 2023 Mar 8;26(4):106358. doi: 10.1016/j.isci.2023.106358. PMID: 36994077; PMCID: PMC10040735.
Tommasini D, Fogel BL. multiWGCNA: an R package for deep mining gene co-expression networks in multi-trait expression data. BMC Bioinformatics. 2023 Mar 24;24(1):115. doi: 10.1186/s12859-023-05233-z. PMID: 36964502; PMCID: PMC10039544.

*If you need WGCNA codes for different applications with video turorial consider using the original works (with video tutorials) by Dr. Steve Horvath, Dr. Peter Langfelder and Dr. Jeremy Miller:
Langfelder, P., Horvath, S. WGCNA: an R package for weighted correlation network analysis. BMC Bioinformatics 9, 559 (2008). https://doi.org/10.1186/1471-2105-9-559
Miller JA, Horvath S, Geschwind DH. Divergence of human and mouse brain transcriptome highlights Alzheimer disease pathways. Proc Natl Acad Sci U S A. 2010 Jul 13;107(28):12698-703. Epub 2010 Jun 25. PMID: 20616000; PMCID: PMC2906579. https://doi.org/10.1073/pnas.0914257107

Video: Dr. Steve Horvath Weighted gene co-expression network analysis https://youtu.be/rRIRMW_RRS4?si=A-ZivIzwdRVLpaLa
Video: Dr. Jeremy Miller How WGCNA Can be Used to Compare and Contrast Two Networks https://youtu.be/aBD67YmCBK4?si=eW9Ybv2nIWDUjkdT
Full Playlist: WGCNA https://www.youtube.com/playlist?list=PLtlynCnS_vmB2kwhfkcfxIDbsSO9uniM5
Resources: Dr. Peter Langfelder lists further resources on his website https://peterlangfelder.com/2018/11/25/wgcna-resources-on-the-web/

Best regards, 
Shradha Mukherjee
https://gitlab.com/smukher2
https://github.com/smukher2
https://orcid.org/0000-0002-3249-2551
https://pubmed.ncbi.nlm.nih.gov/?term=Shradha+Mukherjee

**Comment by smukher2deplatformed** [comment]
FogelLab https://fogellab.neurology.ucla.edu/lab-members/ and Tommasini Dario https://www.linkedin.com/in/dario-tommasini plagerised my work http://tinyurl.com/bde788x2 & deplatformed me on GitHub https://gitlab.com/smukher2 LinkedIn https://www.linkedin.com/in/smukher2/

Don't de-platform them like they did to me because we all deerve freedom of speech and right to know, but use your judgement so that their injusice is not repeated. As users and employers fire them, defunding them, not using their work.

**Comment by dariotommasini** [comment]
Hi @GettyScience , 

I've finally implemented the PreservationPermutationTest function. If you're still interested in running the permutation test used in the paper, please see the updated astrocyte vignette which now has a detailed example of how to use this new function. Please let me know if there are any issues, as it's still very experimental.
