### ISSUE TITLE
constructNetworks() gives error attempt to set 'rownames' on an object with no dimensions

### ISSUE THREAD

**Issue by M-Arafat** [fogellab/multiWGCNA#9]
Hi, I wanna express my admiration with multiWGCNA. I am trying to use it on my data but when i use the function constructNetworks() it gives the following error 
Error in `rownames<-`(`*tmp*`, value = traitData[match(rownames(datExpr2),  : 
  attempt to set 'rownames' on an object with no dimensions

The whole code
DM_networks = constructNetworks(se, sampleTable= meta, conditions1,condition2,
                                    networkType = "unsigned", power = 10,
                                    minModuleSize = 5, maxBlockSize = 250,
                                    reassignThreshold = 0, minKMEtoStay = 0.7,
                                    mergeCutHeight = 0.10, numericLabels = TRUE,
                                    pamRespectsDendro = FALSE, verbose=3)
#-----------------------------------------
my input:
se
class: SummarizedExperiment 
dim: 369 18 
metadata(0):
assays(1): counts
rownames(369): A0A024R6I7 A0A068LKP9 ... Q5JQN9 Q5NV82
rowData names(1): row.names.expdata.
colnames(18): X12B X12BB ... X14_A7 X14_AA7
colData names(3): Sample Status tissue

meta
DataFrame with 18 rows and 3 columns
             Sample      Status      tissue
        <character> <character> <character>
X12B           X12B      before    pancreas
X12BB         X12BB      before    pancreas
X13B           X13B      before    pancreas
X13BB         X13BB      before    pancreas
X14B           X14B      before    pancreas
...             ...         ...         ...
X12_AA7     X12_AA7      after7    pancreas
X13_A7       X13_A7      after7    pancreas
X13_AA7     X13_AA7      after7    pancreas
X14_A7       X14_A7      after7    pancreas
X14_AA7     X14_AA7      after7    pancreas

conditions1
[1] "before" "after2" "after7"

**Comment by dariotommasini** [comment]
Hi @M-Arafat , 

To be honest, I don't remember too well the formatting requirements when using the SummarizedExperiment class. I would try to make sure everything is as similar to the SummarizedExperiment object used in the vignette, since that one does work. 

Also, please send me your session info so we can see if it's a version issue. 

Thanks!

**Comment by janvalddius** [comment]
[counts_matrix_raw.txt] (https://github.com/fogellab/multiWGCNA/files/13672286/counts_matrix_raw.txt)
[Multi_WGCNA.txt]       (https://github.com/fogellab/multiWGCNA/files/13673427/Multi_WGCNA.txt)


I tried to apply multiWGCNA with my data. A matrix counts with 135 samples but I just select one family and removed one infection point (T24)

I create the coldata based on the sample names of the counts to have the same order and names, and then I create the variables.

In my case, I have two conditions,
Condition 1 = 3  ages (4, 16 and 28 months old,  coded as C3, C7 and C8, respectively)   
Condition 2 = 4 points of exposure to infection (code as T0, T3, T6 and T12)

Then I applied the soft_power and ran the network construction

....

and in the end I obtained this:
..removing 61 genes from module 24 because their KME is too low.
 ..merging modules that are too close..
     mergeCloseModules: Merging modules whose distance is less than 0.1
       Calculating new MEs...
 softConnectivity: FYI: connecitivty of genes with less than 45 valid samples will be returned as NA.
 ..calculating connectivities....100% 
Error in datExpr[, !colnames(datExpr) %in% c("X", "kTotal", "kWithin",  : 
  número incorreto de dimensiones (incorrect number of dimensions)

and the other error is something about duplicated genes when I tried to use the most similar format as the tutorial.

**Comment by M-Arafat** [comment]
Thank you for your fast reply. I have been trying many times with other datasets trying to get the consensus module using multiWGCNA and WGCNA pkgs, the thing is when I increase the dimension of my data- to have more features- the error goes away both for multiWGCNA and WGCNA. Is there is any parameter to change or any way to manipulate the source code to accept low dimensional data either for multiWGCNA or WGCNA?

**Comment by dariotommasini** [comment]
How many features do you have? MultiWGCNA simply calls WGCNA blockwiseModules function so if it causes an error for WGCNA then multiWGCNA will fail too. And which error are you referring to?

**Comment by smukher2** [comment]
PLEASE HELP STOP PLAGIARISM AND VILLAINOUS SCIENTISTS BRENT FOGEL (UCLA) AND DARIO TOMMASINI (now PhD student in UC Berkeley) BY NOT CITING OR USING THIS, OR THEIR OTHER CODES AND PAPERS BY THEM. INSTEAD USE AND CITE THE ORIGINAL WORKS (WITH VIDEO TUTORIAL) BY DR. STEVE HORVATH, DR. PETER LANGFELDER AND DR. JEREMY MILLER.(details below)

*For details about wrong doings by Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini
please see open letter at http://tinyurl.com/bde788x2 or file 'This To Apprise You About Wrong Doings By Brent Fogel including and not limited to plagiarism by Brent Fogel and Dario Tommasini.pdf' posted at https://gitlab.com/smukher2/openletter that I also emailed to UCLA, UC Berkeley, iScience and BMC Bioinformatics reporting plagiarism by Brent Fogel and Dario Tommasini in their two papers using this multiWGCNA code https://github.com/fogellab/multiWGCNA:
Tommasini D, Fox R, Ngo KJ, Hinman JD, Fogel BL. Alterations in oligodendrocyte transcriptional networks reveal region-specific vulnerabilities to neurological disease. iScience. 2023 Mar 8;26(4):106358. doi: 10.1016/j.isci.2023.106358. PMID: 36994077; PMCID: PMC10040735.
Tommasini D, Fogel BL. multiWGCNA: an R package for deep mining gene co-expression networks in multi-trait expression data. BMC Bioinformatics. 2023 Mar 24;24(1):115. doi: 10.1186/s12859-023-05233-z. PMID: 36964502; PMCID: PMC10039544.

*If you need WGCNA codes for different applications with video turorial consider using the original works (with video tutorials) by Dr. Steve Horvath, Dr. Peter Langfelder and Dr. Jeremy Miller:
Langfelder, P., Horvath, S. WGCNA: an R package for weighted correlation network analysis. BMC Bioinformatics 9, 559 (2008). https://doi.org/10.1186/1471-2105-9-559
Miller JA, Horvath S, Geschwind DH. Divergence of human and mouse brain transcriptome highlights Alzheimer disease pathways. Proc Natl Acad Sci U S A. 2010 Jul 13;107(28):12698-703. Epub 2010 Jun 25. PMID: 20616000; PMCID: PMC2906579. https://doi.org/10.1073/pnas.0914257107

Video: Dr. Steve Horvath Weighted gene co-expression network analysis https://youtu.be/rRIRMW_RRS4?si=A-ZivIzwdRVLpaLa
Video: Dr. Jeremy Miller How WGCNA Can be Used to Compare and Contrast Two Networks https://youtu.be/aBD67YmCBK4?si=eW9Ybv2nIWDUjkdT
Full Playlist: WGCNA https://www.youtube.com/playlist?list=PLtlynCnS_vmB2kwhfkcfxIDbsSO9uniM5
Resources: Dr. Peter Langfelder lists further resources on his website https://peterlangfelder.com/2018/11/25/wgcna-resources-on-the-web/

Best regards, 
Shradha Mukherjee
https://gitlab.com/smukher2
https://github.com/smukher2
https://orcid.org/0000-0002-3249-2551
https://pubmed.ncbi.nlm.nih.gov/?term=Shradha+Mukherjee

**Comment by smukher2deplatformed** [comment]
FogelLab https://fogellab.neurology.ucla.edu/lab-members/ and Tommasini Dario https://www.linkedin.com/in/dario-tommasini plagerised my work http://tinyurl.com/bde788x2 & deplatformed me on GitHub https://gitlab.com/smukher2 LinkedIn https://www.linkedin.com/in/smukher2/

Don't de-platform them like they did to me because we all deerve freedom of speech and right to know, but use your judgement so that their injusice is not repeated. As users and employers fire them, defunding them, not using their work.
